# Generated by Django 5.0.2 on 2025-03-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='code',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='area_of_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.municipality'),
        ),
    ]
