# Generated by Django 5.0.2 on 2025-03-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_province_region_barangay_municipality_province_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barangay',
            table='tbl_barangay',
        ),
    ]
