# Generated by Django 5.0.2 on 2025-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_barangay_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
