# Generated by Django 5.0.2 on 2025-03-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_barangay_code_alter_barangay_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
