# Generated by Django 5.0.2 on 2025-03-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='address_psgc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.barangay'),
        ),
    ]
