# Generated by Django 5.0.2 on 2025-03-04 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_payroll_payrolldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('fund_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'tbl_fund_sources',
            },
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Released', 'Released')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('liquidation_id', models.AutoField(primary_key=True, serialize=False)),
                ('liquidation_date', models.DateField()),
                ('total_liquidated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to='main_app.payroll')),
            ],
            options={
                'db_table': 'tbl_liquidations',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('obligation_id', models.AutoField(primary_key=True, serialize=False)),
                ('obligation_date', models.DateField()),
                ('amount_obligated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('fund_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='main_app.fundsource')),
            ],
            options={
                'db_table': 'tbl_obligations',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='obligation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='main_app.obligation'),
        ),
    ]
