# Generated by Django 5.0.2 on 2025-03-04 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_fundsource_alter_payroll_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='age',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='biometric_fp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_encoded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='date_paid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_registered',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
