# Generated by Django 5.0.2 on 2025-03-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_beneficiary_age_beneficiary_biometric_fp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_pantawid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='pantawid_hhid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='pantawid_lowb',
            field=models.IntegerField(blank=True, choices=[(1, 'Survival'), (2, 'Subsistence'), (3, 'Self-Sufficient')], null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='biometric_fp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
