# Generated by Django 5.0.2 on 2025-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_beneficiary_email_beneficiary_is_pantawid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Waitlisted', 'Waitlisted'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive'), ('Waived', 'Waived'), ('Moved-out without notice', 'Moved-out without notice')], default='Active', max_length=25),
        ),
    ]
