# Generated by Django 5.0.2 on 2025-03-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.IntegerField(choices=[(2, '2 - Active'), (1, '1 - Waitlisted'), (3, '3 - Deceased'), (4, '4 - Inactive'), (5, '5 - Waived'), (6, '6 - Moved-out without notice'), (7, '7 - Ineligible')], default=1),
        ),
    ]
