# Generated by Django 5.0.2 on 2025-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
