# Generated by Django 5.0.2 on 2025-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_audittrail_delete_beneficiarychangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RenameField(
            model_name='audittrail',
            old_name='date_changed',
            new_name='changed_at',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='field_name',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='changed_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
