# Generated by Django 5.0.2 on 2025-03-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_audittrail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='date_registered',
        ),
    ]
