# Generated by Django 5.0.2 on 2025-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_beneficiary_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='date_registered',
            field=models.DateTimeField(null=True),
        ),
    ]
