# Generated by Django 5.0.2 on 2025-03-05 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_beneficiary_date_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_encoder_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_user_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
