# Generated by Django 5.0.2 on 2025-03-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_beneficiary_encoded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_registered',
            new_name='date_recommended',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='date_validated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_validator_beneficiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
