# Generated by Django 5.0.2 on 2025-03-05 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_beneficiary_approved_by_beneficiary_date_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='certified_correct_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_qa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='certified_correct_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
