# Generated by Django 5.0.2 on 2025-03-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_beneficiary_certified_correct_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_encoded',
            new_name='encoded_dt',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_validated',
            new_name='validated_dt',
        ),
    ]
