# Generated by Django 5.0.2 on 2025-03-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_rename_date_encoded_beneficiary_encoded_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_recommended',
            new_name='recommended_dt',
        ),
    ]
