# Generated by Django 5.0.2 on 2025-03-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_date_recommended_beneficiary_recommended_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_approved',
            new_name='approved_dt',
        ),
    ]
