# Generated by Django 5.0.2 on 2025-03-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_rename_date_approved_beneficiary_approved_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='last_updated',
            new_name='last_updated_dt',
        ),
    ]
