# Generated by Django 5.0.2 on 2025-03-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_beneficiary_encoded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='validated_dt',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tras_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_validation', to='main_app.benetransaction'),
        ),
    ]
