# Generated by Django 5.0.2 on 2025-03-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_beneficiary_validated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='approved_dt',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='certified_correct_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='certified_correct_dt',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='recommended_dt',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tras_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_approval', to='main_app.benetransaction'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tras_qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_qa', to='main_app.benetransaction'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tras_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_recomm', to='main_app.benetransaction'),
        ),
    ]
