# Generated by Django 5.0.2 on 2025-03-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_beneficiary_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('mimetype', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=10)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beneficiary')),
            ],
            options={
                'db_table': 'tbl_pictures',
            },
        ),
    ]
