# Generated by Django 5.0.2 on 2025-03-06 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='tras_approval',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='tras_encoding',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='tras_qa',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='tras_recommendation',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='tras_validation',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='approved_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='certified_correct_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_qa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='certified_correct_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_encoding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='encoded_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_recomm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='recommended_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_waitlisted_validation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='validated_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
