# Generated by Django 5.0.2 on 2025-03-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_remove_beneficiary_tras_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='name_exit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='name_exit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
