# Generated by Django 5.0.2 on 2025-03-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_beneficiary_name_exit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeneTransaction',
        ),
    ]
