# Generated by Django 5.0.2 on 2025-03-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_delete_benetransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='name',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='barangay',
            old_name='code',
            new_name='brgy_code',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='code',
            new_name='muni_code',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='name',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='code',
            new_name='prov_code',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='name',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='code',
            new_name='reg_code',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
    ]
