# Generated by Django 5.0.2 on 2025-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_rename_name_barangay_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='barangay',
            new_name='barangay_name',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='municipality',
            new_name='municipality_name',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='province',
            new_name='province_name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='region_name',
        ),
    ]
