# Generated by Django 5.0.2 on 2024-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('progress', models.FloatField(default=0, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('time_added', models.DateTimeField(null=True)),
                ('checkpoint_time', models.DateTimeField(null=True)),
                ('checkpoint_entry', models.IntegerField(default=0, null=True)),
                ('classification', models.IntegerField(default=0, null=True)),
                ('threshold', models.IntegerField(default=90, null=True)),
                ('limit', models.IntegerField(default=5, null=True)),
                ('scoring_method', models.CharField(blank=True, max_length=15, null=True)),
                ('user_id', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
