# Generated by Django 5.0.2 on 2024-05-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='recent_task_guid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='request_id',
            field=models.CharField(max_length=36),
        ),
    ]
