# Generated by Django 5.0.2 on 2024-05-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0002_tasks_recent_task_guid_alter_tasks_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='recent_task_guid',
            new_name='process_id',
        ),
    ]
