# Generated by Django 5.0.2 on 2024-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0003_rename_recent_task_guid_tasks_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='row_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
