# Generated by Django 5.0.2 on 2024-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0004_tasks_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
