# Generated by Django 5.0.2 on 2024-11-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0007_rename_task_id_datasets_dataset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tractions',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_id', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('progress', models.FloatField(default=0, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('time_added', models.DateTimeField(null=True)),
                ('checkpoint_time', models.DateTimeField(null=True)),
                ('checkpoint_entry', models.IntegerField(default=0, null=True)),
                ('process_id', models.CharField(max_length=36, null=True)),
                ('classification', models.IntegerField(default=0, null=True)),
                ('threshold', models.IntegerField(default=90, null=True)),
                ('limit', models.IntegerField(default=5, null=True)),
                ('scoring_method', models.CharField(blank=True, max_length=15, null=True)),
                ('user_id', models.IntegerField(default=1, null=True)),
                ('row_count', models.IntegerField(default=0, null=True)),
                ('task_type', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
