# Generated by Django 5.0.2 on 2024-11-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0010_rename_request_id_datasets_dataset_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tractions',
            new_name='transactions',
        ),
    ]
