# Generated by Django 5.0.2 on 2024-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0012_alter_transactions_dataset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='lib_trans_class',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='classification',
            new_name='classification_id',
        ),
    ]
