# Generated by Django 5.0.2 on 2024-11-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0013_lib_trans_class_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lib_trans_class',
            new_name='lib_classification',
        ),
    ]
