# Generated by Django 5.0.2 on 2024-11-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0014_rename_lib_trans_class_lib_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='classification_id',
            field=models.ForeignKey(db_column='classification_id', on_delete=django.db.models.deletion.CASCADE, to='dedupe_app.lib_classification'),
        ),
    ]
