# Generated by Django 5.0.2 on 2024-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0015_alter_transactions_classification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='deleted_by',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_deleted',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
