# Generated by Django 5.0.2 on 2024-11-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0016_transactions_date_deleted_transactions_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='classification_id',
            field=models.ForeignKey(db_column='classification_id', on_delete=django.db.models.deletion.PROTECT, to='dedupe_app.lib_classification'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='dataset_id',
            field=models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.PROTECT, to='dedupe_app.datasets'),
        ),
    ]
