# Generated by Django 5.0.2 on 2024-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0017_alter_transactions_classification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='from_roster',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
