# Generated by Django 5.0.2 on 2024-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0019_remove_transactions_from_roster_datasets_from_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans_status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='status',
            new_name='status_id',
        ),
    ]
