# Generated by Django 5.0.2 on 2024-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0020_trans_status_rename_status_transactions_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='lib_trans_status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='trans_status',
        ),
    ]
