# Generated by Django 5.0.2 on 2025-02-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe_app', '0028_alter_datasets_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lib_classification',
            table='lib_classification',
        ),
        migrations.AlterModelTable(
            name='lib_dataset_status',
            table='lib_dataset_status',
        ),
        migrations.AlterModelTable(
            name='lib_trans_status',
            table='lib_trans_status',
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='tbl_transactions',
        ),
    ]
